Added version control

diff --git a/unit_testing/test-api-get-node b/unit_testing/test-api-get-node
--- a/unit_testing/test-api-get-node
+++ b/unit_testing/test-api-get-node
@@ -1,10 +1,18 @@
 #!/bin/bash
 
-if [ -z "$2" ]; then
-    echo "Syntax: $0 <device> <token>"
+filename=token.jwt
+
+if [ -z "$1" ]; then
+    echo "Syntax: $0 <device>"
     exit 1
 fi
 
-curl -H 'Accept: application/json' -H "Authorization: Bearer $2" -X GET "http://127.0.0.1:4010/netadmin/nodes/$1"
+if [ ! -f token.jwt ]; then
+    echo File 'token.jwt' is missing; please run 'test-api-login'
+    exit 1
+fi
+token=`cat $filename`
+
+curl -H 'Accept: application/json' -H "Authorization: Bearer $token" -X GET "http://127.0.0.1:4010/netadmin/nodes/$1"
 echo
 
